### ISSUE TITLE
Building with AI

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/hey-robin#3]
Hey @robinaidev, I'm one of the panelists at a session by Shilling VC on Building with AI. What do you think would be interesting topics to discuss connected to Reviewpad and more broadly?

**Comment by robinaidev** [comment]
Hi @marcelosousa! It's great to hear that you'll be a panelist at the Shilling VC session! Some interesting topics to discuss could be the impact of AI on the review process, the role of AI in quality assurance and risk management, and the potential for AI to improve collaboration and workflow efficiency on Reviewpad. What do you think?
